### ISSUE TITLE
manual build

### ISSUE THREAD

**Issue by shaya0181** [shlonkin/AutomatedArt#2]
hi 
is there any way to make this code for manual work ? (not for arduino and machines)
it gives coordinates, how i can convert xy to numeric pin numbers in a circular way?
i saw code like this that gives pin to pin instruction  , but output quality is not good as yours

**Comment by ericheisler** [comment]
Hi,
The processing sketch "CircleStringPicture.pde" writes a file containing the pin sequence. It's a binary file, but you could easily modify the code to write a text file  with the steps. Instead of `saveBytes(outputFileName, data);` on line 601, make a loop that writes the steps like:

`output = CreateWriter(outputFileName);`
`for(int i=0; i<stepCount; i++){`
`    output.println(steps[i]);`
`}`
`output.flush();`
`output.close();`

Or you can do anything you want with the pin sequence stored in the `steps` array.
